require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "sandbox/*"
    - 'vendor/bundle/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - "spec/features/**/*_spec.rb"

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/MultipleExpectations:
  Exclude:
    - "spec/features/**/*_spec.rb"

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/NamedSubject:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only
