require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

Bundler/OrderedGems:
  Enabled: false

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/NamedSubject:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only
